### ISSUE TITLE
`s3_backup_bucket` is might be redundant

### ISSUE THREAD

**Issue by kamoljan** [microservices-today/IaC-mongodb-s3#2]
s3_backup_bucket = "dummy"
s3_backup_path = "dummy/dummy"

**Comment by alexraju** [comment]
https://github.com/microservices-today/IaC-mongodb-s3/pull/8

`s3_backup_path` is the path to the s3 folder containing the MongoDB dump files and must include the bucket name. Eg: `bucket_name/dir1/dir2`
Also, updated README.md with more description on this. 

`s3_backup_bucket` variable is used to set IAM role for MongoDB instance to access the S3 bucket.
